### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by perfectdeveloper53** [sobanarshad85/BlueTooth_React_Native_integrated#1]
Hello. I tried to run your source code but getting error now.

May you send me apk so i can try it on my side?  If possible, I'd like to cooperate with you on my project. Thanks @sobanarshad85

**Comment by sobanarshad85** [comment]
Thanks for getting back to me.

Currently I am travelling, be sure as i get free I'll send you.

You also can contact me at whatsapp using +923034645060

And kindly let me know what error you are facing.

Bundle of thanks.

Soban Arshad
Software Engineer.

**Comment by perfectdeveloper53** [comment]
i tried react-native run-android to test on android platform.
But i am unable to run it on my android device.

Do you know what the reason is?

Meanwhile, if you would send me apk for testing right now, that would be great. Because I need it urgently for demo show.

Good journey

**Comment by perfectdeveloper53** [comment]
@sobanarshad85  are you sure this runs perfectly without error ?

**Comment by sobanarshad85** [comment]
Copy the repository then run npm install and then run react-native
run-android
It'll start perfectly.

I am extremely sorry i am not having the apk along me, and as i told you i
am travelling, thats why you have to wait for a while.
Hopefully tomorrow i'll be able to semd you.

What error you are facing now?

**Comment by perfectdeveloper53** [comment]
i tried react-native run-android but it does not work

**Comment by sobanarshad85** [comment]
Did you install node_modules by running "npm install"?

**Comment by perfectdeveloper53** [comment]
of course

**Comment by perfectdeveloper53** [comment]
getting erros from react-native-bluetooth-serial.

like @override error

**Comment by perfectdeveloper53** [comment]
that would be great if you send apk tomorrow.
awaiting

**Comment by perfectdeveloper53** [comment]
Hi @sobanarshad85  are you back?

**Comment by sobanarshad85** [comment]
ok, I'm sorry for getting late, I'm here with the solution.
I strongly believe you are using react-antive > 0.47

anyway,
 go into node_modules then react-native-bluetooth-serial => android => src
=> main => java => com => rusel => RCTBluetoothSerial =>
RCTBluetoothSerialPackage.java

and do comment the override this way

// @Override
public List<Class<? extends JavaScriptModule>> createJSModules() {
return Collections.emptyList();
}

instead of

@Override
public List<Class<? extends JavaScriptModule>> createJSModules() {
return Collections.emptyList();
}

and good to go . Kindly do let me know if it solves the error, and gives
you build.
Thanks.

**Comment by sobanarshad85** [comment]
> getting erros from react-native-bluetooth-serial.
> 
> like @override error

issue is resolved now.

**Comment by perfectdeveloper53** [comment]
okay will try myself.
meanwhile,can you send me apk ?

**Comment by sobanarshad85** [comment]
Don't worry issue is all resolved now. You can generate the APK, as I'm
currently busy. Be sure issue is resolved.

**Comment by perfectdeveloper53** [comment]
commited to repository?

**Comment by sobanarshad85** [comment]
as it's a node_module based issue, can't push to repository. In previous
comment I have written the method to overcome this issue.

**Comment by perfectdeveloper53** [comment]
ah okay i got u

**Comment by sobanarshad85** [comment]
Okay, for now, I'm closing this issue.

**Comment by perfectdeveloper53** [comment]
Hi @sobanarshad85 
I just followed your descriptions but unable to build project into apk for testing.

It is better for you to send me apk. If it works enough as we expected, we can invite you to our project.

**Comment by sobanarshad85** [comment]
share your email id.

**Comment by sobanarshad85** [comment]
[app-release.zip](https://github.com/sobanarshad85/BlueTooth_React_Native_integrated/files/3176015/app-release.zip)

Here you go, I haven't completed the working, the basic task was to integrate bluetooth and that is done, your device will turn on/off bluetooth using buttons given inside the app, your device will find out unpaired devices aroung.

More you can check by installing.

**Comment by perfectdeveloper53** [comment]
thanks. let me try

**Comment by perfectdeveloper53** [comment]
i just installed and it only find 1 device though original bluetooth setting find more.

can you help us about this point?

**Comment by sobanarshad85** [comment]
I think it's not problematic for demo purpose.
By the way I'll check what issue it is.

**Comment by perfectdeveloper53** [comment]
unfortunately, it causes problem with our investors.
Because they want stable function as bluetooth is main on our project.

If it doesn't find other devices, app never be good.  :(
